steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/second-elf-455617-d7/delarosa-assign3-image', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/second-elf-455617-d7/delarosa-assign3-image']

timeout: 600s
serviceAccount: 'projects/second-elf-455617-d7/serviceAccounts/my-service-account@second-elf-455617-d7.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY

